apiVersion: apps/v1beta2 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: www-deployment
spec:
  selector:
    matchLabels:
      app: www
  replicas: 2 
  template:
    metadata:
      labels:
        app: www
    spec:
      containers:
      - name: www
        image: tutum/hello-world
        ports:
        - containerPort: 80
